# -*- makefile -*-

top_srcdir = ..\..\..\..
top_builddir = ..\..\..\..

!INCLUDE $(top_srcdir)/vcc/Makefile.build

LOCAL_CFLAGS =					\
	$(CPPCUTTER_CFLAGS)

LOCAL_LDFLAGS =					\
	$(CPPCUTTER_LDFLAGS)

LIBS =						\
	$(GLIB_LIBS)				\
	cutter.lib				\
	cppcutter.lib

!INCLUDE $(top_srcdir)/vcc/Makefile.test.fixtures.loader.cpp-fixture

all: $(tests)

clean:
	@del $(tests)
