# -*- makefile -*-

top_srcdir = ..\..\..\..

!INCLUDE $(top_srcdir)/vcc/Makefile.build

LOCAL_CFLAGS =					\
	$(GCUTTER_CFLAGS)

LOCAL_LDFLAGS =					\
	$(GCUTTER_LDFLAGS)

LIBS =						\
	$(GLIB_LIBS)				\
	cutter.lib

!INCLUDE $(top_srcdir)/vcc/Makefile.test.fixtures.type1

all: $(tests)

clean:
	@del $(tests)
