# -*- makefile -*-

top_srcdir = ../

SUBDIRS =	\
	source

all:
	for %d in ($(SUBDIRS)) do			\
		$(MAKE) -nologo -f Makefile.win32 sub DIRECTORY=%d TARGET=all

sub:
	@cd $(DIRECTORY)
	@$(MAKE) -nologo -f Makefile.win32 $(TARGET)
	@cd ..
