# -*- makefile -*-

top_srcdir = ..
top_builddir = ..

!INCLUDE $(top_srcdir)/vcc/Makefile.build
!INCLUDE $(top_srcdir)/vcc/Makefile.objects.gcutter

LOCAL_CFLAGS = $(GCUTTER_CFLAGS)

LIBS =							\
	$(GLIB_LIBS)

OBJS =				\
	$(LIBGCUTTER_OBJECTS)

all: $(OBJS)
