# -*- makefile -*-

top_srcdir = ..\..\..
top_builddir = ..\..\..

!INCLUDE $(top_srcdir)/vcc/Makefile.build

LOCAL_CFLAGS =							\
	-DCUT_RELATIVE_PATH="\"fixtures\\test-context\""	\
	$(GCUTTER_CFLAGS)

LOCAL_LDFLAGS =					\
	$(GCUTTER_LDFLAGS)

LIBS =						\
	$(GLIB_LIBS)				\
	cutter.lib

!INCLUDE $(top_srcdir)/vcc/Makefile.test.fixtures.test-context

all: $(tests)

clean:
	@del $(tests)
