# -*- makefile -*-

top_srcdir = ../../

SUBDIRS =	\
	gcutter	\
	cutter

all:
	for %d in ($(SUBDIRS)) do			\
		$(MAKE) -nologo -f Makefile.win32 sub DIRECTORY=%d TARGET=all

clean:
	for %d in ($(SUBDIRS)) do			\
		$(MAKE) -nologo -f Makefile.win32 sub DIRECTORY=%d TARGET=clean

sub:
	@cd $(DIRECTORY)
	@$(MAKE) -nologo -f Makefile.win32 $(TARGET)
	@cd ..
