# -*- makefile -*-

top_srcdir = ..
top_builddir = ..

!INCLUDE $(top_srcdir)/vcc/Makefile.build
!INCLUDE $(top_srcdir)/vcc/Makefile.objects.cutter
!INCLUDE $(top_srcdir)/vcc/Makefile.objects.gcutter

LOCAL_CFLAGS = $(GCUTTER_CFLAGS)

LIBS =							\
	$(GLIB_LIBS)

OBJS =				\
	$(LIBCUTTER_OBJECTS)	\
	$(LIBGCUTTER_OBJECTS)

all: cutter.dll

clean:
	@del $(OBJS)

cutter.dll: $(OBJS)
	$(CC) $(CFLAGS) -LD -Fe$@ $(OBJS) $(LIBS) $(LDFLAGS) /implib:cutter.lib
