# -*- makefile -*-

top_srcdir = ..\..
top_builddir = ..\..

!INCLUDE $(top_srcdir)/vcc/Makefile.build

LOCAL_CFLAGS =					\
	$(GCUTTER_CFLAGS)			\
	$(GTK_CFLAGS)

LOCAL_LDFLAGS =					\
	$(GCUTTER_LDFLAGS)			\
	$(GTK_LDFLAGS)				\
	/libpath:$(top_builddir)\test\lib	\
	$(USE_MSVCRT_LDFLAGS)

LIBS =						\
	$(GTK_LIBS)				\
	cutter.lib				\
	cuttest-utils.lib

test_cut_stream_parser_LDFLAGS =		\
	cuttest-event-receiver.lib

!INCLUDE $(top_srcdir)/vcc/Makefile.test.cutter

all: $(tests)

clean:
	@del $(tests)
